services:
  app-server:
    image: ghcr.io/gh7254/registry:${IMAGE_TAG}
    container_name: todo_app_container
    restart: unless-stopped

    ports:
      - "3003:3000"

    extra_hosts:
      - "host.docker.internal:host-gateway"

    environment:
      NODE_ENV: ${NODE_ENV}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}
      OTEL_EXPORTER_OTLP_ENDPOINT: http://host.docker.internal:4317
      OTEL_SERVICE_NAME: todo-app
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: todo-db
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

    ports:
      - "3307:3306"

    volumes:
      - mysql-data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 30s

  pyroscope:
    image: grafana/pyroscope:latest
    container_name: pyroscope
    restart: unless-stopped
    ports:
      - "4040:4040"
volumes:
  mysql-data:
