services:

  app-server:
    image: ghcr.io/gh7254/registry:${IMAGE_TAG}

    container_name: todo_app_container

    ports:
      - "3003:3000"

    environment:
      NODE_ENV: ${NODE_ENV}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}

    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: todo-db
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

    ports:
      - "3307:3306"

    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
